apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-3
  template:
    metadata:
      labels:
        app: spring-app-3
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"

        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "spring-app-3-role"
        vault.hashicorp.com/agent-inject-secret-db-creds.txt: "secret/data/spring-app-3/db"
        vault.hashicorp.com/agent-inject-template-db-creds.txt: |
          {{- with secret "secret/data/spring-app-3/db" -}}
          export DB_USERNAME="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
    spec:
      serviceAccountName: spring-app-sa
      containers:
        - name: spring-app-3
          image: spring-app-3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # args: ["-c", "source /vault/secrets/db-creds.txt && java -jar app.jar"]