spring:
  application:
    name: inputhttpserver

server:
  port: 8080

grpc:
  client:
    grpcserver:
      address: grpcserver
      port: 9090

logging:
  level:
    com.example.inputhttpserver.config.LoggingClientInterceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  prometheus:
    metrics:
      export:
        enabled: true 