apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-4
  template:
    metadata:
      labels:
        app: spring-app-4
    spec:
      containers:
      - name: spring-app-4
        image: spring-app-4:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-4-service
spec:
  selector:
    app: spring-app-4
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30080 # Uncomment and set if you want a specific NodePort
  type: NodePort  #