apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-1
  template:
    metadata:
      labels:
        app: spring-app-1
    spec:
      containers:
      - name: spring-app-1
        image: spring-app-1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-1-service
spec:
  selector:
    app: spring-app-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer