# application-rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-1-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-app-1-configmap-reader
subjects:
  - kind: ServiceAccount
    name: spring-app-1-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-reader