# configuration-watcher-rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
  labels:
    app: spring-cloud-kubernetes-configuration-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-watcher
rules:
  # Allow watcher to get, list and watch ConfigMaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow watcher to get endpoints to find application pods
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-kubernetes-configuration-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-watcher
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-configuration-watcher