apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    spring.cloud.kubernetes.secret: "true"
  annotations:
    spring.cloud.kubernetes.secret.apps: "spring-app-4-service"
type: Opaque
stringData:
  application.yml: |-
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/book_db
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: user
        password: password