apiVersion: v1
kind: ConfigMap
metadata:
  name: logbook-config
  labels:
    spring.cloud.kubernetes.config: "true"
    spring.cloud.kubernetes.secret: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "spring-app-1-service" # will find all the pods match the service's selector to refresh the config in parallel: Sending refresh request for spring-app-1-service to URI http://10.244.0.43:8080/actuator/refresh
data:
  application.yml: |-
    logbook:
      body:
        filter:
          patterns:
            - pattern: "\\b\\d{4}[- ]?\\d{4}[- ]?\\d{4}[- ]?\\d{4}\\b"
              replacement: "****-****-****-$4"
            - pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
              replacement: "****@$1"
            - pattern: "\"password\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"password\":\"****\""
            - pattern: "\"secret\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"secret\":\"****\""
            - pattern: "\"creditCard\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"creditCard\":\"****\""
            - pattern: "\"cardNumber\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"cardNumber\":\"****\""
            - pattern: "\"privateKey\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"privateKey\":\"****\""
            - pattern: "\"token\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"token\":\"****\""
            - pattern: "\"apiKey\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"apiKey\":\"****\""
            - pattern: "\"ssn\"\\s*:\\s*\"[^\"]*\""
              replacement: "\"ssn\":\"****\""