server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  aop:
    auto: true
    proxy-target-class: true

  cloud:
    vault:
      uri: http://host.docker.internal:8200
      scheme: http
      token: my-spring-app-1-token
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: spring-app-1
        application-name: spring-app-1
      config:
        # Add these settings
        watch:
          enabled: true
        refresh-interval: 30000  # 30 seconds
  config:
    import:
      - "optional:vault://"
      - "optional:file:app/config/logging/"
      - "optional:file:app/config/resilience/"

# enable this to see otel logs in console
# otel:
#   exporter:
#     logging:
#       enabled: true
#   traces:
#     exporter: logging
#   metrics:
#     exporter: none

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: INFO
    org.zalando.logbook: TRACE
    org.springframework.vault: DEBUG
    # enable this to see otel logs in console
    # io.opentelemetry.exporter.otlp: DEBUG
    # io.opentelemetry.sdk.trace.export: DEBUG
    # io.opentelemetry: DEBUG

  file:
    path: logs/

logbook:
  format.style: json
  include: /**  # This ensures all paths are logged
  exclude: /actuator/**  # Optional exclusions
  obfuscate:
    headers:
      - Authorization
      - X-API-Key
    parameters:
      - password
      - secret
      - creditCard
      - cardNumber
  write:
    chunk-size: 1000