   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: oracle-db
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: oracle-db
     template:
       metadata:
         labels:
           app: oracle-db
       spec:
         containers:
         - name: oracle-db
           image: container-registry.oracle.com/database/free:23.6.0.0-lite-arm64
           ports:
           - containerPort: 1521
           env:
           - name: ORACLE_PWD
             value: YourSecurePassword  # Set a secure password
           volumeMounts:
           - mountPath: /opt/oracle/oradata
             name: oracle-storage
         volumes:
         - name: oracle-storage
           persistentVolumeClaim:
             claimName: oracle-pvc