mode: deployment
image:
  repository: otel/opentelemetry-collector
config:
  exporters:
    debug: {}
    otlp:
      endpoint: http://my-tempo.monitoring:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        exporters: [otlp, debug]