server:
  port: 8082

spring:
  application:
    name: step2service

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always 