spring:
  application:
    name: service-a

server:
  port: 8080

grpc:
  client:
    service-b:
      address: localhost # This will be overridden by Docker Compose to 'service-b'
      port: 9090

logging:
  level:
    com.example.servicea.config.LoggingClientInterceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  prometheus:
    metrics:
      export:
        enabled: true
