apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-3
  template:
    metadata:
      labels:
        app: spring-app-3
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"

        # inject secrets into /vault/secrets/application.properties
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/role: "spring-app-3-role"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/spring-app-3/db"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/spring-app-3/db" -}}
          spring.datasource.url={{ index .Data.data "spring.datasource.url" }}
          spring.datasource.driver-class-name={{ index .Data.data "spring.datasource.driver-class-name" }}
          spring.datasource.username={{ index .Data.data "spring.datasource.username" }}
          spring.datasource.password={{ index .Data.data "spring.datasource.password" }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-application.properties: |
          curl -s -X POST http://localhost:8080/actuator/refresh
    spec:
      serviceAccountName: spring-app-sa
      containers:
        - name: spring-app-3
          image: spring-app-3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # read secrets imported from /vault/secrets/ folder
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/vault/secrets/