apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "springapp-role"
    vault.hashicorp.com/agent-inject-secret-hello.txt: "secret/data/hello"
    vault.hashicorp.com/agent-inject-template-hello.txt: |
      {{- with secret "secret/data/hello" -}}
      hello={{ .Data.data.value }}
      {{- end }}
spec:
  serviceAccountName: default
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]