server:
  port: 8080

spring:
  # datasource:
  #   url: jdbc:otel:${SPRING_DATASOURCE_URL:mysql://localhost:3306/demodb}
  #   username: ${SPRING_DATASOURCE_USERNAME}
  #   password: ${SPRING_DATASOURCE_PASSWORD}
  #   driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  aop:
    auto: true
    proxy-target-class: true

# enable this to see otel logs in console
otel:
  exporter:
    logging:
      enabled: true
  traces:
    exporter: logging
  metrics:
    exporter: none

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: INFO
    org.zalando.logbook: TRACE
    # enable this to see otel logs in console
    io.opentelemetry.exporter.otlp: DEBUG
    io.opentelemetry.sdk.trace.export: DEBUG

  file:
    path: logs/

logbook:
  format.style: json
  include: /**  # This ensures all paths are logged
  exclude: /actuator/**  # Optional exclusions
  obfuscate:
    headers:
      - Authorization
      - X-API-Key
    parameters:
      - password
      - secret
      - creditCard
      - cardNumber
  write:
    chunk-size: 1000