apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-vietinbank-paymenthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com-vietinbank-paymenthub
  template:
    metadata:
      labels:
        app: com-vietinbank-paymenthub
      annotations:
        prometheus.io/scrape: "true"  # Enable Prometheus scraping
        prometheus.io/port: "8080"    # Specify the metrics port
        prometheus.io/path: "/actuator/prometheus"  # Metrics endpoint (change if needed)
    spec:
      containers:
      - name: com-vietinbank-paymenthub
        image: com-vietinbank-paymenthub:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: com-vietinbank-paymenthub-service
  # annotations:
  #   prometheus.io/scrape: "true"  # Enable scraping for Prometheus via service discovery
  #   prometheus.io/port: "8080"    # Specify the metrics port
  #   prometheus.io/path: "/actuator/prometheus"  # Metrics endpoint (modify if needed)
spec:
  selector:
    app: com-vietinbank-paymenthub
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30080 # Uncomment and set if you want a specific NodePort
  type: NodePort  