spring:
  application:
    name: account-service
    instance_id: instance-1
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  cloud:
    discovery:
      enabled: true
# Enable gRPC server
grpc:
  server:
    port: 9595
    address: 0.0.0.0
  client:
    account-service:
      address: 'discovery:///account-service'
#      address: 'static://localhost:9595'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    transaction-service:
      address: 'discovery:///transaction-service'
#      address: 'static://localhost:9494'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    fraud-detection-service:
      address: 'discovery:///fraud-detection-service'
#      address: 'static://localhost:9696'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    lease-renewal-interval-in-seconds: 5
    durationInSeconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      grpc.port: ${grpc.server.port}

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
